# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jerrylou Blog
author: Jerrylou
authorurl: /index.html
email: gunsluo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  我是个Coder，懒的什么也没有留下。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jerrylou.me" # the base hostname & protocol for your site
exclude:
   - Gemfile
   - Gemfile.lock
   - jekyll.thor

# Build settings
# markdown: kramdown
highlighter: pygments
markdown: redcarpet
redcarpet:
 extensions:
   - fenced_code_blocks
   - no_intra_emphasis
   - strikethrough
   - autolink
   - tables
   - highlight
   - superscript
   - with_to_data

#pagination
gems: [jekyll-paginate, jekyll-assets]
paginate: 5
paginate_path: "/page:num/"

assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache: false
  cache_type: filesystem
  cdn: 
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
    - "bundle.css"
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
